### ISSUE TITLE
Support security schemes

### ISSUE THREAD

**Issue by dpnolte** [lg-backbone/kompendium#14]
Hi,

This is great 💯 I was looking for a minimally invasive open api spec generator.
I need the support of security schemes (basic auth and jwt token).

That is, the security scheme would be added to the spec, for instance:
```
  "components" : {
    "securitySchemes" : {
      "basic_auth" : {
        "scheme" : "basic",
        "type" : "http"
      }
    }
  },
```
and that the scheme would be added where appropriate:
```
  "paths" : {
    "/api/v1/status" : {
      "get" : {
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        },
        "security" : [ {
          "basic_auth" : [ ]
        } ]
      }
    },
 }
```

I was wondering if I could submit a PR for this. If so, do you have a particular api in mind?
I was thinking perhaps something like: ```notarizedAuthorization(name = "basic_auth") { .. }```
This would be wrapper around Ktor's `authentication` method. The Kompendium object would then need to keep track of the current scheme that is in scope.  What do you think?

**Comment by rgbrizzlehizzle** [comment]
Hey just saw this, glad you like it! I have used a couple of the other doc generators out there and they each had some baggage or weirdness that I didn't like... trying to address that with Kompendium 😄 

Yea security schemas are a must, I had it a bit lower on my list since I'm still just knocking out the core functionality right now... would love for you to put a PR out for it! 

If you haven't you should probably pull the most recent code, I did a complete rehaul of the reflections today, hopefully should clean it up a lot.  

As for the actual implementation... I need to dig into how Ktor authentication works, but that seems reasonable at a glance.  But would `notarizedAuthorization` be responsible for generating both the path content _and_ the `components.SecuritySchema` code?  

My general approach so far has been to try to keep as much in the `components` block as possible, as that allows you to have really light weight implementation details that then use the JSON Schema `$ref` ability to point to their respective information.

**Comment by rgbrizzlehizzle** [comment]
Ok, looking at the spec details here https://swagger.io/docs/specification/authentication I have a couple thoughts... 

An alternative to what you proposed would be to add an authentication field to the `MethodInfo` that is passed to each `notarized` operation.  

I think this has a couple pros and a couple cons

Pros 

1. In keeping with minimal invasiveness... if people want to remove Kompendium, I really like the idea of their API working by just replacing `notarizedGet` with `get` and so on.  
2. Allows us to leverage the existing route analysis that Kompendium already does and apply permissions on an individual method basis

Cons

1. It's odd to have a ktor `authentication` method, but specify the auth documentation at a different level
2. Where would the declaration of "all available" auth methods go? 

On that last point, It could be declared directly, since the total pool of auth methods just needs to be declared once, it may be overkill to do anything other than to just declare it at the point that you expose the API. 

Hope that makes some sense, mostly just a brain dump at this point
